### ISSUE TITLE
Make the interface where bazels3cache binds configurable

### ISSUE THREAD

**Issue by jcpetruzza** [Asana/bazels3cache#18]
At the moment one can configure the port where `bazels3cache` will listen, but the interface is hardcoded to `localhost`. This means that:

  - The only workflow supported is for `bazels3cache` to run on the same machine where `bazel` is being used (instead of, say, sharing a cache for all  devs).
  - Even on that worklow, one can't distribute it using `docker`, since the port cannot be exposed to the host.

**Comment by mmorearty** [comment]
Good suggestion, thanks. Re: the first bullet point, I think that's actually covered with the current behavior — it's true that each dev will be running their own copy of `bazels3cache`, but `bazels3cache` is simply a thin proxy that passes all requests through to S3. So for example, the way we use it is that all devs are pointing at the same S3 bucket, thus they have a shared cache. Furthermore, S3 is built with scalability in mind, whereas `bazels3cache` — while fast — was not built with the intent of serving large numbers of clients from a single instance. Certainly it is capable of doing so, but I haven't thought much about the scalability implications of that.

Your second point about the `docker` scenario is compelling. Plus, who knows what other arbitrary reasons someone might have for wanting to put it somewhere other than `localhost` — the tool should not restrict your options.

I'll add a `--host` command-line option, and a corresponding `"host": "localhost"` in `config.default.json`. (Or you are welcome to tackle this and contribute it if you like.)

**Comment by mmorearty** [comment]
Fixed!

**Comment by mmorearty** [comment]
Published version 1.0.2 to npm

**Comment by jcpetruzza** [comment]
Thanks for the super quick response! :clap:  Will try it out now!
